In [5]:
import torch
import torch.nn.functional as F


logits = torch.randn(20, 32)
# Sample soft categorical using reparametrization trick:
F.gumbel_softmax(logits, tau=0.1, hard=False)


tensor([[2.2102e-10, 3.9148e-15, 2.9365e-18, 1.5961e-15, 1.3409e-12, 2.8981e-17,
         1.5778e-22, 9.8378e-14, 1.8506e-19, 7.7633e-01, 2.7155e-18, 3.8764e-18,
         1.0584e-20, 2.6768e-19, 2.5684e-19, 3.4015e-03, 1.0468e-02, 1.1967e-16,
         2.0586e-09, 2.7888e-14, 6.7711e-25, 3.6105e-11, 3.8069e-13, 1.8915e-15,
         2.0980e-01, 2.9422e-07, 5.8647e-16, 1.8916e-13, 6.3899e-21, 5.4088e-19,
         6.2213e-17, 6.8612e-12],
        [1.6984e-13, 1.1410e-26, 1.2459e-26, 2.5165e-24, 5.6686e-20, 6.3293e-17,
         2.0084e-14, 1.4295e-21, 2.9663e-18, 8.0986e-15, 1.3513e-25, 1.4806e-14,
         2.3789e-22, 2.1126e-22, 8.1734e-23, 1.8114e-21, 1.6943e-35, 9.9948e-01,
         5.2441e-23, 1.4814e-29, 9.6140e-24, 2.6122e-32, 3.2339e-24, 1.5902e-22,
         2.6713e-26, 1.7086e-17, 1.6101e-16, 2.3597e-09, 2.2949e-13, 8.8789e-16,
         5.1606e-04, 1.8047e-19],
        [1.7587e-07, 8.8177e-06, 1.9049e-25, 6.6455e-37, 9.9992e-01, 8.6175e-14,
         5.8799e-22, 3.7129e-09, 8.2713e-

In [7]:
F.gumbel_softmax(logits, tau=0.00001, hard=False)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 

In [4]:
# Sample hard categorical using "Straight-through" trick:
F.gumbel_softmax(logits, tau=1, hard=True)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 

In [2]:
logits

tensor([[ 5.8363e-01, -8.9883e-02, -1.0143e+00, -1.0225e+00,  1.8367e+00,
          8.6901e-01,  4.4488e-01,  3.4503e-01,  1.2014e+00,  4.0037e-01,
          2.1278e-01, -1.7271e+00, -3.9537e-01,  1.5334e+00,  3.2885e-01,
         -9.1263e-01, -2.0075e+00, -1.3030e+00, -3.4437e-01,  3.1877e-01,
          3.9635e-01,  3.5699e-01,  1.4358e+00,  7.3515e-01, -6.5388e-01,
          1.5688e+00,  4.1479e-01,  1.5717e-01, -4.6981e-01, -1.7940e+00,
          4.3301e-01, -1.7378e+00],
        [-6.9368e-01,  6.1279e-01, -6.1076e-01,  2.2498e-01, -1.3317e-01,
         -9.8731e-01,  1.1369e+00,  6.3350e-01, -1.1849e+00,  8.6850e-01,
         -1.9089e+00, -8.9819e-01,  3.4603e-01, -1.0291e+00, -6.0982e-01,
          1.1703e+00,  1.5763e+00,  8.1099e-01,  3.5406e-01,  3.9889e-01,
          8.2279e-01,  2.7433e-01,  1.3866e+00, -5.9254e-01,  8.0528e-01,
          1.9053e+00, -2.7344e-02,  3.9246e-01,  1.3263e+00, -2.1546e+00,
         -5.7430e-01, -7.2368e-01],
        [ 9.4518e-01,  1.4045e+00,  9.48